### ISSUE TITLE
我有苹果账号啊，但可能因为图片不能上架啊

### ISSUE THREAD

**Issue by iHTCboy** [lijinshanmx/flutter_gank#1]
现在苹果对应用要求比较高，大量诱惑的图片是不能上架的，具体苹果审核条款：

1.1.4 过于色情的内容 (韦氏词典对“色情”一词的定义是：对性器官或性活动的露骨描述或展示，目的在于刺激性快感，而非带来美学价值或触发情感)。

https://developer.apple.com/cn/app-store/review/guidelines/

@lijinshanmx  看看可以授权给我来送审？我可以试试啊

**Comment by lijinshanmx** [comment]
好啊，可以过审前服务器控制不显示哪些功能，然后等过审后再看情况是否打开就行，你加我微信吧，详聊一下:lijinshan_ybn

**Comment by lijinshanmx** [comment]
ios端还需要添加一些插件代码，以及额外的一些代码，才能上线，最好是了解flutter编码的iOS开发者，所以先暂时搁置，如果你是ios开发者而且正好又熟悉或者正在学习flutter，可以私下详聊~
