### ISSUE TITLE
[Issue] Now, can't build

### ISSUE THREAD

**Issue by JaeWangL** [lijinshanmx/flutter_gank#12]

**Comment by Gracker** [comment]
Compiler message:
lib/ui/page/page_history.dart:44:51: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
                      buildDefaultFooter(context, mode, () {
                                                  ^
lib/ui/page/page_history.dart:42:34: Error: The argument type 'Widget Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, RefreshStatus)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'Widget Function(BuildContext, RefreshStatus)'.
                  headerBuilder: buildDefaultHeader,
                                 ^
lib/ui/widget/indicator_factory.dart:23:11: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
    mode: mode,
          ^
lib/ui/widget/indicator_factory.dart:32:17: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
          mode: mode,
                ^
lib/ui/widget/indicator_factory.dart:43:15: Error: The argument type 'int' can't be assigned to the parameter type 'RefreshStatus'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'RefreshStatus'.
        mode: mode,
              ^
lib/ui/page/page_detail.dart:74:30: Error: The argument type 'Widget Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, RefreshStatus)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'Widget Function(BuildContext, RefreshStatus)'.
              headerBuilder: buildDefaultHeader,
                             ^
lib/ui/page/page_welfare.dart:57:51: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
                      buildDefaultFooter(context, mode, () {
                                                  ^
lib/ui/page/page_welfare.dart:55:34: Error: The argument type 'Widget Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, RefreshStatus)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'Widget Function(BuildContext, RefreshStatus)'.
                  headerBuilder: buildDefaultHeader,
                                 ^
lib/ui/page/page_new.dart:60:28: Error: The argument type 'Widget Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, RefreshStatus)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'Widget Function(BuildContext, RefreshStatus)'.
            headerBuilder: buildDefaultHeader,
                           ^
lib/ui/page/page_favorite.dart:85:30: Error: The argument type 'Widget Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, RefreshStatus)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'Widget Function(BuildContext, RefreshStatus)'.
              headerBuilder: buildDefaultHeader,
                             ^
lib/ui/widget/widget_list_category.dart:44:47: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
                  buildDefaultFooter(context, mode, () {
                                              ^
lib/ui/widget/widget_list_category.dart:42:30: Error: The argument type 'Widget Function(BuildContext, int)' can't be assigned to the parameter type 'Widget Function(BuildContext, RefreshStatus)'.
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('file:///home/oneplus/Software/flutter/packages/flutter/lib/src/widgets/framework.dart').
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///home/oneplus/Software/flutter/.pub-cache/hosted/pub.dartlang.org/pull_to_refresh-1.2.0/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'Widget Function(BuildContext, RefreshStatus)'.
              headerBuilder: buildDefaultHeader,
                             ^
Compiler failed on /home/oneplus/Github/flutter_gank/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by lijinshanmx** [comment]
@Gracker  你升级了下拉刷新控件的版本,它里面有个不兼容的更新,你需要把/lib/ui/widget/indicator_factory.dart这个文件的里面的int mode参数,改成RefreshStatus即可.

**Comment by lijinshanmx** [comment]
(BuildContext context, int mode)  =>  (BuildContext context, RefreshStatus mode) 即可.
pull_to_refresh: ^1.1.6     = >  pull_to_refresh: 1.2.0
