### ISSUE TITLE
你好，我是一名android开发者，准备做一款自己的应用，请问你的UI设计是怎么做的

### ISSUE THREAD

**Issue by TsaiYongChuan** [lijinshanmx/flutter_gank#16]
就是怎么设计出Material design风格

**Comment by lijinshanmx** [comment]
https://www.material.io/components/
Material design是一套标准，Android标准控件就支持的。

**Comment by TsaiYongChuan** [comment]
道理我都懂，问题是UI谁帮你设计的，你说的控件是实现过程，在前面又是谁提供了给你UI设计，我感觉很好看

**Comment by lijinshanmx** [comment]
你好，可以参考一些第三方App的UI实现，比如你要做一个android视频播放器，那么你就可以参考优酷或者腾讯视频的界面。

**Comment by TsaiYongChuan** [comment]
现在就是做的这款是个工业APP，同行都好丑，不知道怎么设计才能更美观，求解

**Comment by lijinshanmx** [comment]
那这个就需要专门找个设计人员简单的设计个界面，花费一定得费用就行。

**Comment by lijinshanmx** [comment]
https://www.ui.cn/list.html?tag=0&r=edit&subcatid=4&catid=0&timeid=0

**Comment by TsaiYongChuan** [comment]
好的，谢谢解答

**Comment by lijinshanmx** [comment]
上面的这些app模板，你看能不能参考下。
