### ISSUE TITLE
Finished with error: FormatException: Bad UTF-8 encoding 0xe4 (at offset 9)

### ISSUE THREAD

**Issue by lijinshanmx** [lijinshanmx/flutter_gank#2]
运行的时候，出现：Finished with error: FormatException: Bad UTF-8 encoding 0xe4 (at offset 9)，一种解决方法是:打开设置，把当前语言设置成英文，然后注销，再次运行，应该就ok了，然后再把语言设置为中文。这样就解决了。最终的问题应该就是UFT8编码的问题，我是在mac上开发的，周末没带电脑，想在windows上运行下，结果弄了这么一蛋疼的问题。百度谷歌了好久，最后才通过设置语言解决~~

**Comment by ismlsmile** [comment]
测试了下确实遇到这个问题。但有个事我觉得比较奇怪，为啥其它的项目没遇到这个问题？是不是可以通过项目工程上的一些配置来解决？

**Comment by lijinshanmx** [comment]
@ismlsmile 我也不太清楚，我也是在window上遇到这个问题，折腾了2天，最后就是改变系统语言解决的，我在mac上都没问题的，文件编码都是正常的uft-8.具体这个问题，可以关注这个issue[flutter/issues/15646](https://github.com/flutter/flutter/issues/15646)

**Comment by ismlsmile** [comment]
这个issue当时我也搜到了，所以刚开始觉得这个问题是正常的。但后来试了其它的项目都没啥问题，就一直觉得应该是可以通过工程方面的设置来解决

**Comment by hsir05** [comment]
我也遇到这个问题了，按照上面所说的，修改之后，问题解决了

**Comment by JeffSuu** [comment]
我想问一下，是在电脑设置，还是在as里面设置？

**Comment by JeffSuu** [comment]
我想问一下，是在电脑设置，还是在as里面设置？

**Comment by lijinshanmx** [comment]
@JeffSuu 电脑的

**Comment by JeffSuu** [comment]
> @JeffSuu 电脑的

好的，谢谢您

**Comment by ismlsmile** [comment]
@lijinshanmx 这问题我已经试出来怎么不改系统配置，只改工程配置解决了。

flutter_gank工程中，android目录下没有gradlew文件，用Android Studio打开后，会自动生成一个gradlew文件。拿另外一个正常的工程的这个文件，把刚才自动生成的gradlew文件替换掉，就可以正常编译了。

我比较了一下这两个文件，内容完全一样，差别只在换行符。自动生成不可用的换行符是\n，工作正常的换行符是\r\n。

至于为啥会导致这个原因，我也不太清楚了。对Android和gradle都不太熟，只是业余随便玩玩，知道原因的同学可以帮忙解释下。

**Comment by lijinshanmx** [comment]
@ @ismlsmile 嗯，我稍后看一下，如果是这样，我更新下gradlew文件即可.

**Comment by Hiwen** [comment]
我是在做多语言支持时，遇到这个问题的。我使用VS Code在Windows 10上进行的开发。
尝试了很多办法，都不行！
后来 把我的两个语言映射文件：i18n_en.json和i18n_zh.json用UTF-8保存一下，问题解决！
保存方法如下：
![image](https://user-images.githubusercontent.com/13505993/67154612-fcb24780-f331-11e9-9145-90181a631615.png)
