### ISSUE TITLE
关于iOS本地的反馈

### ISSUE THREAD

**Issue by CaiJingLong** [lijinshanmx/flutter_gank#8]
我看到你的iOS端反馈还没有做
要是你还没找到人,我最近有时间的话可以帮做下

**Comment by lijinshanmx** [comment]
@CaiJingLong 好啊，好啊，十分欢迎~  我这边最近特别忙，你可以先用自己的测试账号，把基本功能都打通，然后提交PR，我merge以后，再把key改成线上key即可。

**Comment by CaiJingLong** [comment]
iOS的反馈我这里做完了,一会儿提交一个PR
我看到你的TODOLIST有两项:检查更新获取版本号
这两项我没有找到阿里云的SDK,有连接吗?

**Comment by lijinshanmx** [comment]
@CaiJingLong 检查获取新版本，好像appstore会提示的，如果有新版本提交，app就简单的提示一下有新版本即可，然后跳转到appstore。所以需要写插件 调用oc或者swift获取到app的版本号，然后对比服务器端和本地的版本号。
`   public void checkUpdate(UpdateCallback updateCallback) {
        String path = Environment.getExternalStorageDirectory().getAbsolutePath();
        Map<String, String> params = new HashMap<>();

        params.put("appKey", "ab5dce55Ac4bcW408cPb8c2Aaeac179c5f6g");
        params.put("version", AppUpdateUtils.getVersionName(this));

        new UpdateAppManager
                .Builder()
                .setActivity(this)
                .setHttpManager(new OkGoUpdateHttpUtil())
                .setUpdateUrl("https://gank.io/api/checkversion")
                .setPost(true)
                .setParams(params)
                .setTargetPath(path)
                .dismissNotificationProgress()
                .build()
                .checkNewApp(updateCallback);
    }`

**Comment by lijinshanmx** [comment]
@CaiJingLong 加我微信:lijinshan_ybn,我把ios反馈配置文件发你.

**Comment by CaiJingLong** [comment]
iOS中的更新,我的做法是请求 https://itunes.apple.com/cn/lookup?id=414478124 类似于这种接口
然后解析json 这个id是iTunes Connect 分配给应用的
[wechat.json](https://github.com/lijinshanmx/flutter_gank/files/2928712/1.1.txt)

```dart
var map = json.decode(value.data);
var netVersion = map["results"][0]["version"];
PackageInfo packageInfo = await PackageInfo.fromPlatform();
var version = packageInfo.version;

var compareVersion = Version.parse(netVersion).compareTo(Version.parse(version));
if (result > 0) {
  // 需要更新, 直接跳appstore 
  launch("https://itunes.apple.com/cn/app/%E9%A3%9F%E8%BF%85%E9%9A%8F%E8%BA%AB/id1286979692");
} else { 
 // 不需要更新
}
```

**Comment by lijinshanmx** [comment]
@CaiJingLong  【Gank服务器 https://gank.io/api/checkversion】 这个接口可以返回是不是有新版本，只要把当前version传过去，我后端会做校验，当然你的这种也可以，毕竟App Store是最吊的哈😝.行，可以的话，你就PR吧，我merge一下。

**Comment by CaiJingLong** [comment]
#11  
目前使用的checkversion这个接口
可能后面需要加入platform的请求参数

如果iOS端要用app store的版本号等app store的应用申请下来我可以再PR

**Comment by lijinshanmx** [comment]
@CaiJingLong 好的~
